"""Builds static/phrases.json — the conversational chunks shown in the catalog Mini App.

Hand-picked, not generated: ready-made pieces natives say whole (fillers, connectors,
reactions, polite formulas, frames with a slot). Neutral Spanish by default; `region`
marks the few that are mostly Spain ("es") or mostly Latin America ("la") — Ольга's
list is aimed at Latin America, so region-specific ones are labelled rather than mixed in
silently.

Edit the table below and re-run:  python tools/build_phrases.py
"""

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "static" / "phrases.json"

DATA = [
    ("Заполнители и паузы", [
        ("pues…", "ну…", ""),
        ("bueno…", "ну / ладно", ""),
        ("o sea", "то есть", ""),
        ("es que…", "дело в том, что…", ""),
        ("la verdad…", "честно говоря…", ""),
        ("digamos", "скажем", ""),
        ("a ver…", "так, сейчас… / ну-ка", ""),
        ("¿sabes?", "знаешь?", ""),
        ("¿me entiendes?", "понимаешь меня?", ""),
        ("total, que…", "в общем…", ""),
        ("en fin", "в общем / ну да ладно", ""),
        ("este…", "э-э… (заминка в речи)", "la"),
        ("en plan", "типа", "es"),
        ("tipo", "типа", "la"),
    ]),
    ("Начать мысль", [
        ("para empezar", "для начала", ""),
        ("te cuento", "слушай, рассказываю", ""),
        ("resulta que…", "оказывается…", ""),
        ("el caso es que…", "дело в том, что…", ""),
        ("una cosa…", "слушай, такой вопрос…", ""),
        ("quería preguntarte…", "хотел(а) у тебя спросить…", ""),
        ("mira…", "слушай…", ""),
        ("oye…", "слушай / эй", ""),
    ]),
    ("Связки", [
        ("además", "кроме того", ""),
        ("por eso", "поэтому", ""),
        ("así que", "так что", ""),
        ("entonces", "тогда / значит", ""),
        ("sin embargo", "однако", ""),
        ("aunque", "хотя", ""),
        ("de todos modos", "в любом случае", ""),
        ("por otro lado", "с другой стороны", ""),
        ("en cambio", "зато / а вот", ""),
        ("mientras tanto", "тем временем", ""),
        ("al final", "в итоге", ""),
        ("por cierto", "кстати", ""),
        ("es decir", "то есть", ""),
        ("por ejemplo", "например", ""),
        ("sobre todo", "особенно", ""),
        ("en general", "в целом", ""),
        ("en resumen", "короче говоря", ""),
        ("en realidad", "на самом деле", ""),
        ("de hecho", "вообще-то, по факту", ""),
        ("por lo menos", "по крайней мере", ""),
    ]),
    ("Закончить мысль", [
        ("y ya está", "и всё", ""),
        ("eso es todo", "это всё", ""),
        ("nada más", "больше ничего", ""),
        ("para terminar", "в завершение", ""),
        ("en pocas palabras", "если коротко", ""),
        ("algo así", "что-то вроде того", ""),
        ("o algo por el estilo", "или что-то в этом роде", ""),
    ]),
    ("Согласие", [
        ("claro", "конечно", ""),
        ("claro que sí", "ну конечно да", ""),
        ("por supuesto", "разумеется", ""),
        ("exacto", "точно", ""),
        ("tienes razón", "ты прав(а)", ""),
        ("estoy de acuerdo", "я согласен(на)", ""),
        ("totalmente", "полностью согласен(на)", ""),
        ("me parece bien", "мне подходит", ""),
        ("de acuerdo", "договорились", ""),
        ("vale", "окей", "es"),
        ("dale", "давай, окей", "la"),
        ("listo", "готово / идёт", "la"),
        ("¡hecho!", "договорились!", ""),
    ]),
    ("Несогласие и сомнение", [
        ("no estoy de acuerdo", "я не согласен(на)", ""),
        ("no creo", "не думаю", ""),
        ("para nada", "вовсе нет", ""),
        ("ni hablar", "и речи быть не может", ""),
        ("depende", "смотря как", ""),
        ("no sé…", "не знаю…", ""),
        ("tengo mis dudas", "у меня есть сомнения", ""),
        ("no me convence", "меня это не убеждает", ""),
        ("puede ser", "может быть", ""),
        ("a lo mejor", "возможно", ""),
        ("quizás", "может быть", ""),
        ("supongo que sí", "наверное, да", ""),
        ("claro que no", "конечно нет", ""),
        ("¡qué va!", "да ну, вовсе нет", "es"),
    ]),
    ("Реакции", [
        ("¡qué bien!", "как хорошо!", ""),
        ("¡qué pena!", "как жаль!", ""),
        ("¡qué lástima!", "какая жалость!", ""),
        ("¡qué raro!", "как странно!", ""),
        ("¡no me digas!", "да ладно!", ""),
        ("¿en serio?", "серьёзно?", ""),
        ("¡vaya!", "ого / надо же", ""),
        ("¡menos mal!", "слава богу", ""),
        ("¡qué suerte!", "какая удача!", ""),
        ("¡genial!", "отлично!", ""),
        ("¡increíble!", "невероятно!", ""),
        ("¡ay, no!", "ой, нет!", ""),
        ("¡qué horror!", "какой ужас!", ""),
        ("¡qué rico!", "как вкусно!", "la"),
        ("¡qué guay!", "как круто!", "es"),
    ]),
    ("Вежливость и просьбы", [
        ("¿me puedes ayudar?", "можешь мне помочь?", ""),
        ("¿podrías…?", "не мог(ла) бы ты…?", ""),
        ("¿te importa si…?", "не против, если…?", ""),
        ("¿me pasas…?", "передашь мне…?", ""),
        ("¿me haces un favor?", "сделаешь одолжение?", ""),
        ("con permiso", "разрешите (пройти)", ""),
        ("disculpa", "извини", ""),
        ("disculpe", "извините (вежливо)", ""),
        ("perdona la molestia", "прости за беспокойство", ""),
        ("no hay de qué", "не за что", ""),
        ("no te preocupes", "не переживай", ""),
        ("tranquilo / tranquila", "спокойно, всё в порядке", ""),
        ("si no es molestia", "если не сложно", ""),
        ("muchas gracias por todo", "большое спасибо за всё", ""),
    ]),
    ("Переспросить и уточнить", [
        ("¿cómo?", "что, простите?", ""),
        ("¿perdón?", "простите?", ""),
        ("¿me lo repites?", "повторишь?", ""),
        ("más despacio, por favor", "помедленнее, пожалуйста", ""),
        ("no te he entendido", "я тебя не понял(а)", ""),
        ("¿qué significa…?", "что значит…?", ""),
        ("¿cómo se dice … en español?", "как сказать … по-испански?", ""),
        ("¿cómo se escribe?", "как это пишется?", ""),
        ("¿qué quieres decir?", "что ты имеешь в виду?", ""),
        ("a ver si te entiendo", "давай проверю, правильно ли понял(а)", ""),
        ("o sea, que…", "то есть…", ""),
        ("¿estás seguro? / ¿estás segura?", "ты уверен(а)?", ""),
        ("¿puedes hablar más despacio?", "можешь говорить помедленнее?", ""),
        ("¿me lo puedes escribir?", "можешь мне это написать?", ""),
    ]),
    ("Готовые конструкции", [
        ("tengo que…", "мне нужно… (что-то сделать)", ""),
        ("hay que…", "нужно (вообще, безлично)", ""),
        ("acabo de…", "я только что…", ""),
        ("estoy a punto de…", "я вот-вот…", ""),
        ("voy a…", "я собираюсь…", ""),
        ("me gustaría…", "мне бы хотелось…", ""),
        ("necesito…", "мне нужно…", ""),
        ("tengo ganas de…", "очень хочу…", ""),
        ("me da igual", "мне всё равно", ""),
        ("vale la pena", "оно того стоит", ""),
        ("me hace falta…", "мне не хватает…", ""),
        ("suelo…", "я обычно… (делаю что-то)", ""),
        ("lo que pasa es que…", "дело в том, что…", ""),
        ("no hace falta que…", "не нужно, чтобы…", ""),
        ("es mejor que…", "лучше, чтобы…", ""),
        ("hace mucho que…", "уже давно…", ""),
        ("llevo … años aquí", "я здесь … лет", ""),
        ("acabo de llegar", "я только что приехал(а)", ""),
        ("estoy aprendiendo español", "я учу испанский", ""),
        ("se me da bien…", "у меня хорошо получается…", ""),
    ]),
    ("Мнение", [
        ("creo que…", "думаю, что…", ""),
        ("me parece que…", "мне кажется, что…", ""),
        ("en mi opinión", "по-моему", ""),
        ("para mí…", "для меня / по мне…", ""),
        ("la verdad es que…", "правда в том, что…", ""),
        ("pienso que…", "я считаю, что…", ""),
        ("me imagino que…", "полагаю, что…", ""),
        ("sinceramente", "честно говоря", ""),
        ("si te soy sincero / sincera", "если честно", ""),
        ("yo diría que…", "я бы сказал(а), что…", ""),
        ("desde mi punto de vista", "с моей точки зрения", ""),
    ]),
    ("Время и частота", [
        ("ahora mismo", "прямо сейчас", ""),
        ("enseguida", "сейчас же, мигом", ""),
        ("de repente", "вдруг", ""),
        ("de vez en cuando", "время от времени", ""),
        ("a menudo", "часто", ""),
        ("casi nunca", "почти никогда", ""),
        ("siempre que puedo", "всегда, когда могу", ""),
        ("hoy en día", "в наше время", ""),
        ("por ahora", "пока что", ""),
        ("más tarde", "попозже", ""),
        ("un momento", "минутку", ""),
        ("hace poco", "недавно", ""),
        ("dentro de poco", "скоро", ""),
        ("cada vez más", "всё больше", ""),
        ("todavía no", "ещё нет", ""),
        ("ya no", "больше не", ""),
        ("otra vez", "снова", ""),
        ("al rato", "попозже, через какое-то время", "la"),
    ]),
    ("Бытовые ситуации", [
        ("¿cuánto cuesta?", "сколько стоит?", ""),
        ("la cuenta, por favor", "счёт, пожалуйста", ""),
        ("para llevar", "с собой (навынос)", ""),
        ("aquí tiene", "вот, пожалуйста", ""),
        ("¿aceptan tarjeta?", "вы принимаете карту?", ""),
        ("¿dónde está el baño?", "где туалет?", ""),
        ("estoy buscando…", "я ищу…", ""),
        ("¿hay wifi?", "здесь есть вайфай?", ""),
        ("¿cuál me recomienda?", "что посоветуете?", ""),
        ("sin hielo", "безо льда", ""),
        ("para dos personas", "на двоих", ""),
        ("¿está libre?", "свободно?", ""),
        ("¿a qué hora abren?", "во сколько открываетесь?", ""),
        ("solo estoy mirando", "я просто смотрю", ""),
        ("¿tiene algo más barato?", "есть что-нибудь подешевле?", ""),
        ("¿me cobras?", "можно рассчитаться?", "es"),
    ]),
    ("Знакомство и small talk", [
        ("¿qué tal?", "как дела?", ""),
        ("¿cómo va todo?", "как жизнь?", ""),
        ("¿a qué te dedicas?", "чем занимаешься?", ""),
        ("¿de dónde eres?", "откуда ты?", ""),
        ("mucho gusto", "очень приятно", ""),
        ("igualmente", "взаимно", ""),
        ("¿cuánto tiempo llevas aquí?", "давно ты здесь?", ""),
        ("nos vemos", "увидимся", ""),
        ("hasta luego", "до скорого", ""),
        ("cuídate", "береги себя", ""),
        ("saludos a tu familia", "привет твоей семье", ""),
        ("¡qué gusto verte!", "как приятно тебя видеть!", ""),
        ("¿nos vemos mañana?", "увидимся завтра?", ""),
    ]),
    ("Проблемы и извинения", [
        ("lo siento mucho", "мне очень жаль", ""),
        ("fue sin querer", "я не нарочно", ""),
        ("no pasa nada", "ничего страшного", ""),
        ("se me olvidó", "я забыл(а)", ""),
        ("llego tarde", "я опаздываю", ""),
        ("no funciona", "не работает", ""),
        ("me equivoqué", "я ошибся (ошиблась)", ""),
        ("¿qué hago?", "что мне делать?", ""),
        ("necesito ayuda", "мне нужна помощь", ""),
        ("estoy perdido / perdida", "я заблудился (заблудилась)", ""),
        ("tuve un problema", "у меня возникла проблема", ""),
        ("perdón por el retraso", "извините за опоздание", ""),
    ]),
]


def main():
    phrases, seen = [], set()
    for category, rows in DATA:
        for es, ru, region in rows:
            key = es.lower()
            if key in seen:
                raise SystemExit(f"duplicate phrase: {es}")
            seen.add(key)
            phrases.append({
                "n": len(phrases) + 1, "es": es, "ru": ru, "cat": category, "region": region,
            })
    OUT.write_text(
        json.dumps({"categories": [c for c, _ in DATA], "phrases": phrases}, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"{len(phrases)} phrases, {len(DATA)} categories → {OUT}")


if __name__ == "__main__":
    main()
